"""MJPEG over HTTPS server for Local Mode.

Spec §6.2 + §7.3. Serves `multipart/x-mixed-replace` JPEG frames produced by
the `picamera2` MJPEG encoder. Lazy lifecycle: the encoder is asked to
attach when the FIRST client connects and to detach when the LAST one
disconnects (so when nobody's watching, no encoding cost).

HTTP Basic Auth using the `rcs_operator` credential from the local Mosquitto
passwd file. TLS reuses the same self-signed cert/key pair as Mosquitto,
generated by setup.sh.
"""
from __future__ import annotations

import asyncio
import base64
import logging
import ssl
from typing import Awaitable, Callable, Optional

from aiohttp import web

logger = logging.getLogger(__name__)

JPEG_BOUNDARY = "frame"


class MjpegServer:
    """aiohttp server serving /stream.mjpg with BasicAuth and TLS."""

    def __init__(self,
                 bind_host: str,
                 bind_port: int,
                 cert_path: str,
                 key_path: str,
                 auth_username: str,
                 auth_password_hash_check: Callable[[str], bool],
                 attach_encoder: Callable[[], Awaitable[asyncio.Queue]],
                 detach_encoder: Callable[[], Awaitable[None]],
                 endpoint_path: str = "/stream.mjpg"):
        self._bind_host = bind_host
        self._bind_port = bind_port
        self._cert_path = cert_path
        self._key_path = key_path
        self._auth_username = auth_username
        self._auth_password_hash_check = auth_password_hash_check
        self._attach_encoder = attach_encoder
        self._detach_encoder = detach_encoder
        self._endpoint_path = endpoint_path

        self._app: Optional[web.Application] = None
        self._runner: Optional[web.AppRunner] = None
        self._site: Optional[web.TCPSite] = None
        self._client_count = 0
        self._frame_queue: Optional[asyncio.Queue] = None
        self._lock = asyncio.Lock()

    async def start(self) -> None:
        self._app = web.Application()
        self._app.router.add_get(self._endpoint_path, self._handle_stream)

        ssl_ctx = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
        ssl_ctx.load_cert_chain(self._cert_path, self._key_path)

        self._runner = web.AppRunner(self._app)
        await self._runner.setup()
        self._site = web.TCPSite(self._runner, self._bind_host, self._bind_port,
                                 ssl_context=ssl_ctx)
        await self._site.start()
        logger.info("MjpegServer listening on https://%s:%s%s",
                    self._bind_host, self._bind_port, self._endpoint_path)

    async def stop(self) -> None:
        if self._site is not None:
            await self._site.stop()
        if self._runner is not None:
            await self._runner.cleanup()

    async def _handle_stream(self, request: web.Request) -> web.StreamResponse:
        # ---- BasicAuth ----
        if not self._authorize(request):
            return web.Response(status=401,
                                headers={"WWW-Authenticate": 'Basic realm="ugv"'})

        # ---- Lazy encoder attach ----
        async with self._lock:
            self._client_count += 1
            if self._client_count == 1:
                self._frame_queue = await self._attach_encoder()
                logger.info("MJPEG encoder attached (first client)")

        try:
            response = web.StreamResponse(status=200, headers={
                "Content-Type": f"multipart/x-mixed-replace; boundary={JPEG_BOUNDARY}",
                "Cache-Control": "no-cache, no-store, must-revalidate",
                "Pragma": "no-cache",
                "Connection": "close",
            })
            # Disable Nagle for minimum latency
            sock = request.transport.get_extra_info("socket")
            if sock is not None:
                import socket as _s
                sock.setsockopt(_s.IPPROTO_TCP, _s.TCP_NODELAY, 1)

            await response.prepare(request)

            while not request.transport.is_closing():
                try:
                    frame: bytes = await asyncio.wait_for(
                        self._frame_queue.get(), timeout=10.0)
                except asyncio.TimeoutError:
                    logger.warning("MJPEG encoder produced no frame in 10s")
                    break
                part = (
                    f"--{JPEG_BOUNDARY}\r\n"
                    f"Content-Type: image/jpeg\r\n"
                    f"Content-Length: {len(frame)}\r\n\r\n"
                ).encode("ascii") + frame + b"\r\n"
                try:
                    await response.write(part)
                except (ConnectionResetError, RuntimeError):
                    break
            return response
        finally:
            async with self._lock:
                self._client_count -= 1
                if self._client_count == 0:
                    await self._detach_encoder()
                    logger.info("MJPEG encoder detached (last client gone)")

    def _authorize(self, request: web.Request) -> bool:
        header = request.headers.get("Authorization", "")
        if not header.startswith("Basic "):
            return False
        try:
            user, _, password = base64.b64decode(header[6:]).decode().partition(":")
        except Exception:
            return False
        return user == self._auth_username and \
               self._auth_password_hash_check(password)
